name: Swift Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: blacksmith-8vcpu-ubuntu-2404-arm
    container:
      image: swift:6.2-noble

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install System SQLite
        run: |
          apt-get update
          apt-get install -y libsqlite3-dev

      - name: Fix Git permissions
        run: git config --global --add safe.directory '*'

      - name: Resolve & Test
        run: |
          swift package clean
          swift package resolve
          swift test
